### ISSUE TITLE
"Did not successfully decode" when running the example 

### ISSUE THREAD

**Issue by wyjin** [jimbozhang/kaldi-gop#5]
When running the example, I got log entries like this:

`` WARNING (compute-gmm-gop[5.1.113~1-72672]:Decode():gop/gmm-gop.cc:65) Did not successfully decode.
``

 Any insight on fixing this would be appreciated.

**Comment by jimbozhang** [comment]
This message means the audio was very different with the text, or the model was poorly trained.

**Comment by hyuezhi** [comment]
I got the same error too, and I used the **_swbd_model_tri1.tar.gz_** (which include the model and the test data).

Any thing reply from you would be great appreciated.

**Comment by jimbozhang** [comment]
The model may not well matches the data. Issue #9 is to use models from http://kaldi-asr.org/downloads/tree/trunk. Hopefully it could address this problem.

**Comment by hyuezhi** [comment]
thank you, and I realized maybe it's the correct output, but there are just 20+ sentences got the wrong answer. I am going to record some my own voice to test for it~  

great thanks

**Comment by mkperez808** [comment]
I am using a model trained by myself and am grabbing the text produced by the best path through the decoding lattice. I am still getting gop scores produced however, the log file also includes this warning. @jimbozhang Does this warning indicate that the algorithm failed in some critical way? Or can the gop scores produced still be used? Our custom trained system is achieving a WER of 9% (due to the restricted nature of our speech data) so our model is actually pretty decent.
